### ISSUE TITLE
Single host items contain the hostname in the legend

### ISSUE THREAD

**Issue by mingaliev-e** [grafana/grafana-zabbix#1706]
Hi, new version 4.1.1 did not fix the issue https://github.com/grafana/grafana-zabbix/issues/1335
I`m using Grafana v 9.5.5 and zabbix v 5.0

**Comment by gabor** [comment]
hi, the current version of the grafana zabbix plugin is 4.4.1.
based on the changelog at https://github.com/grafana/grafana-zabbix/blob/master/CHANGELOG.md, 

the fix was first available in 4.4.0.

please try with the latest version, it should be fixed there.

(i'll close the issue for now, if the problem still persist, please write back and we can reopen the issue).
