### ISSUE TITLE
Canvas dashboard -  hostname has been removed from item value

### ISSUE THREAD

**Issue by Samendk** [grafana/grafana-zabbix#1721]
Hello,
Starting from plugin version 4.4.x, hostname has been removed from Canvas. Because of this, it is impossible to assemble a large dashboard of hundreds of different hosts with the same item value

If i use Grafana 10.1.5, Zabbix 6.2.9 and plugin 4.3.1
![изображение](https://github.com/grafana/grafana-zabbix/assets/122208948/540d9833-0525-46de-9d62-cc2fba11aa5f)

If i use Grafana 10.1.5, Zabbix 6.2.9 and plugin 4.4.х

![изображение](https://github.com/grafana/grafana-zabbix/assets/122208948/3bcce447-bf26-473f-8df4-8c077483bcd5)

So I can’t use two metrics, since they will have the same names without specifying the host name

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.1.5  | 6.2.9 | 4.4.х                 |
| 10.1.5  | 6.2.9 | 4.3.1                 |

**Comment by zoltanbedi** [comment]
the reason this does not work after the 4.4.0-upgrade, is that you look for the value-field by it's name, and the name of the value field has changed from 4.3.x to 4.4.0. the change is about adding the hostname to the field-name or not.

the specific change happened in this commit: https://github.com/grafana/grafana-zabbix/commit/e33812427ed650e65f60088a4e59105587dd2dd0
which was a fix for an issue raised in https://github.com/grafana/grafana-zabbix/issues/1335

so the current (4.4.x) behaviour is that if you only get data for a single hostname, then there's no hostname in the field-name, otherwise there is a hostname in the field name.

I understand this is a large change, but we cannot revert it, because that would mean introducing one more change for people who started with 4.4.x. so while we'll certainly be more careful with such changes in the future, the current change has to stay in.
(also, based on the linked GitHub issue it seems like this change in 4.4.x is in fact a return to an older (older-than-4.2.0) behaviour)

there is a possible workaround:
you could add aliases to every query, thereby "freezing" those names, so the upgrade would not change them. it would possible to, for example, add aliases on the currently running old-version, then upgrade to new-version and all should be good.

**Comment by Samendk** [comment]
@zoltanbedi I created a new test server with grafana 10.2.0 and plugin 4.4.3

However, if I use multiple hosts, the item name does not contain the host name.
![grafana_source](https://github.com/grafana/grafana-zabbix/assets/122208948/15720b12-9289-4e70-a359-5c2e68b71b7b)

it is not clear on the graph from which host the data was received
![grafana_source_1](https://github.com/grafana/grafana-zabbix/assets/122208948/08e68170-7c8d-4dba-95ec-41f4f9229f91)

**Comment by Samendk** [comment]
If I use the plugin version 4.3.1 then everything is fine
![grafana_source_2](https://github.com/grafana/grafana-zabbix/assets/122208948/b825e3cf-3429-4e2b-aacd-35f6c6041adb)

**Comment by shab2** [comment]
Hello! 
Grafana v10.4.0, Zabbix plugin 4.4.6
What I should exactly do for see hostname in legend?
Now I have in one chart data from 2 hosts. I want see hostname + metric name in legend
Thank you
